<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class ProfilesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('profiles')->insert([
            [
                'provider_id'=>'1',
                'name' => 'Ahmed Khaled Tawfek',
                'email' => 'ahmedkt123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '0123456789',
                'area' =>'Al Manakh District',
                'service' => 'Air Conditioning Service',
                'skills' => json_encode([
                    'Air conditioning cleaning & summer maintenance',
                    'Dismantling and installing Air conditioning'
                ]),
                'photo' => 'images/profile_photos\pro1.jpg',

            ],

            [
                'provider_id'=>'2',
                'name' => 'Mohamed Sami Youssef',
                'email' => 'mohamedsy123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '0987654321',
                'area' => 'Al Zohour District',
                'service' => 'Air Conditioning Service',
                'skills' => json_encode([ 'Dismantling and installing Air conditioning']),
                'photo' => 'images/profile_photos\pro2.jpg',
            ],

            [
                'provider_id'=>'3',
                'name' => 'Khaled Omar Ibrahiem',
                'email' => 'khaledoi123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Air Conditioning Service',
                'skills' => json_encode([ 'Air conditioning inspection',  'Charging Freon air conditioning']),
                'photo' => 'images/profile_photos\pro3.jpg',
            ],

            [
                'provider_id'=>'4',
                'name' => 'Ali Mostafa Zedan',
                'email' => 'alimz123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al-dowahi District',
                'service' => 'Air Conditioning Service',
                'skills' => json_encode(['Air conditioning cleaning & summer maintenance',
                 'Air conditioning inspection',
                 'Charging Freon air conditioning',
                 'Dismantling and installing Air conditioning']),
                 'photo' => 'images/profile_photos\pro4.jpg',
            ],

            [
                'provider_id'=>'5',
                'name' => 'Youssef Soliman Fouad',
                'email' => 'youssefsf123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Air Conditioning Service',
                'skills' => json_encode([ 'Charging Freon air conditioning']),
                'photo' => 'images/profile_photos\pro5.jpg',
            ],

            [
                'provider_id'=>'6',
                'name' => 'Hassan Waleed Kamal',
                'email' => 'hassanwk123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'East Port Said District',
                'service' => 'Air Conditioning Service',
                'skills' => json_encode([ 'Air conditioning inspection','Dismantling and installing Air conditioning']),
                 'photo' => 'images/profile_photos\pro6.jpg',
            ],

            [
                'provider_id'=>'7',
                'name' => 'Marawan Saead Zaher',
                'email' => 'marwansz123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'South District',
                'service' => 'Air Conditioning Service',
                'skills' => json_encode([ 'Air conditioning cleaning & summer maintenance',
                   'Air conditioning inspection',
                   'Charging Freon air conditioning',
                   'Dismantling and installing Air conditioning']),
                   'photo' => 'images/profile_photos\pro7.jpg',
            ],

            [
                'provider_id'=>'8',
                'name' => 'Ibrahiem Samir Nageb',
                'email' => 'ibrahiemsn123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                 'area' =>'Al Manakh District',
                'service' => 'Air Conditioning Service',
                'skills' => json_encode([ 'Air conditioning cleaning & summer maintenance']),
                'photo' => 'images/profile_photos\pro8.jpg',
            ],
            [
                'provider_id'=>'9',
                'name' => 'Tarek Hesham Nabil',
                'email' => 'tarekhn123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                 'area' => 'Al Zohour District',
                'service' => 'Carpentry Service',
                'skills' => json_encode([ 'Door Installation and Repair',
                    'Window Framing and Repair',
                   'Bedroom Furniture Assembly',
                   'Table Crafting and Restoration']),
                   'photo' => 'images/profile_photos\pro9.jpg',
            ],
            [
                'provider_id'=>'10',
                'name' => 'Fares Mahmoud Zaki',
                'email' => 'faresmz123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Carpentry Service',
                'skills' => json_encode(['Door Installation and Repair',  'Table Crafting and Restoration']),
                'photo' => 'images/profile_photos\pro10.jpg',
            ],
            [
                'provider_id'=>'11',
                'name' => 'Noureldeen Sameh Gamal',
                'email' => 'noureldeensg123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Carpentry Service',
                'skills' => json_encode(['Door Installation and Repair',
                    'Window Framing and Repair',
                   'Table Crafting and Restoration']),
                   'photo' => 'images/profile_photos\pro11.jpg',

            ],
            [
                'provider_id'=>'12',
                'name' => 'Samer Ehab Fadel',
                'email' => 'sameref123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'East Port Said District',
                'service' => 'Carpentry Service',
                'skills' => json_encode(['Bedroom Furniture Assembly']),
                'photo' => 'images/profile_photos\pro12.jpg',
            ],

            [
                'provider_id'=>'13',
                'name' => 'Karim Alaa Mansour',
                'email' => 'karimam123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>' Al-dowahi District',
                'service' => 'Carpentry Service',
                'skills' => json_encode(['Door Installation and Repair']),
                'photo' => 'images/profile_photos\pro13.jpg',
            ],

            [
                'provider_id'=>'14',
                'name' => 'Zeyad Nasser Tawfik',
                'email' => 'zeyadnt123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'South District',
                'service' => 'Carpentry Service',
                'skills' => json_encode([ 'Window Framing and Repair', 'Table Crafting and Restoration']),
                'photo' => 'images/profile_photos\pro14.jpg',

            ],

            [
                'provider_id'=>'15',
                'name' => 'Eyad Amr AbdElHameed',
                'email' => 'eyadaad123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Carpentry Service',
                'skills' => json_encode(['Door Installation and Repair',
                      'Window Framing and Repair',
                      'Table Crafting and Restoration']),
                      'photo' => 'images/profile_photos\pro15.jpg',
            ],
            [
                'provider_id'=>'16',
                'name' => 'Sherif Tamer AbdElAzeez',
                'email' => 'sheriftab123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al Manakh District',
                'service' => 'Carpentry Service',
                'skills' => json_encode([ 'Door Installation and Repair',
                   'Window Framing and Repair',
                   'Bedroom Furniture Assembly',
                   'Table Crafting and Restoration']),
                   'photo' => 'images/profile_photos\pro16.jpg',

            ],
            [
                'provider_id'=>'17',
                'name' => 'Ramy Adham Sabri',
                'email' => 'ramyas123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al Zohour District',
                'service' => 'Electrical Work Service',
                'skills' => json_encode([ 'Wiring and Cabling Services',
                'Installing and Maintaining Electrical Panels',
                'Installing and Maintaining Lighting Systems',
                'Installing and Maintaining Alarm and Home Security Systems']),
                'photo' => 'images/profile_photos\pro17.jpg',

            ],
            [
                'provider_id'=>'18',
                'name' => 'Mazen Ayman Radwan',
                'email' => 'mazenar123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'East Port Said District',
                'service' => 'Electrical Work Service',
                'skills' => json_encode(['Installing and Maintaining Alarm and Home Security Systems']),
                'photo' => 'images/profile_photos\pro18.jpg',

            ],
            [
                'provider_id'=>'19',
                'name' => 'Hazem Bassam Rafek',
                'email' => 'hazembr123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Electrical Work Service',
                'skills' => json_encode(['Wiring and Cabling Services', 'Installing and Maintaining Electrical Panels']),
                'photo' => 'images/profile_photos\pro19.jpg',

            ],
            [
                'provider_id'=>'20',
                'name' => 'Haithem Magdi Anwar',
                'email' => 'haithemma123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al Zohour District',
                'service' => 'Electrical Work Service',
                'skills' => json_encode([ 'Installing and Maintaining Lighting Systems']),
                'photo' => 'images/profile_photos\pro20.jpg',

            ],
            [
                'provider_id'=>'21',
                'name' => 'Nader Galal Mohsen',
                'email' => 'nadergm123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al Manakh District',
                'service' => 'Electrical Work Service',
                'skills' => json_encode([ 'Installing and Maintaining Electrical Panels']),
                'photo' => 'images/profile_photos\pro21.jpg',

            ],
            [
                'provider_id'=>'22',
                'name' => 'Basel Adel Hassan ',
                'email' => 'baselah123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Electrical Work Service',
                'skills' => json_encode(['Wiring and Cabling Services',
                'Installing and Maintaining Electrical Panels',
                'Installing and Maintaining Lighting Systems',
                'Installing and Maintaining Alarm and Home Security Systems']),
                'photo' => 'images/profile_photos\pro22.jpg',

            ],
            [
                'provider_id'=>'23',
                'name' => 'Raed Tarek Yassen ',
                'email' => 'raedty123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Electrical Work Service',
                'skills' => json_encode(['Wiring and Cabling Services']),
                'photo' => 'images/profile_photos\pro23.jpg',
            ],

            [
                'provider_id'=>'24',
                'name' => 'Malek Samer Shukri',
                'email' => 'malekssh123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al-dowahi District',
                'service' => 'Electrical Work Service',
                'skills' => json_encode([ 'Installing and Maintaining Electrical Panels','Installing and Maintaining Lighting Systems']),
                'photo' => 'images/profile_photos\pro24.jpg',
            ],
            [
                'provider_id'=>'25',
                'name' => 'Seif Ehab Nader',
                'email' => 'seifen123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'East Port Said District',
                'service' => 'Appliance Service',
                'skills' => json_encode([ 'Washing Machine Repair',
                     'Refrigerator Repair',
                     'Water Heater Repair',
                      'Oven Repair']),
                      'photo' => 'images/profile_photos\pro25.jpg',

            ],
            [
                'provider_id'=>'26',
                'name' => 'Gad Hussien Medhat',
                'email' => 'gadhm123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Appliance Service',
                'skills' => json_encode(['Washing Machine Repair']),
                'photo' => 'images/profile_photos\pro26.jpg',

            ],
            [
                'provider_id'=>'27',
                'name' => 'Salman Hatem Khalil',
                'email' => 'salmanhkh123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al Manakh District',
                'service' => 'Appliance Service',
                'skills' => json_encode(['Oven Repair']),
                'photo' => 'images/profile_photos\pro27.jpg',

            ],
            [
                'provider_id'=>'28',
                'name' => 'Adel Fouad Masoud',
                'email' => 'adelfm123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Appliance Service',
                'skills' => json_encode(['Refrigerator Repair',]),
                'photo' => 'images/profile_photos\pro28.jpg',

            ],
            [
                'provider_id'=>'29',
                'name' => 'Louay Hossam Ramzi',
                'email' => 'louayhr123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al Zohour District',
                'service' => 'Appliance Service',
                'skills' => json_encode([ 'Refrigerator Repair',  'Water Heater Repair']),
                'photo' => 'images/profile_photos\pro29.jpg',

            ],
            [
                'provider_id'=>'30',
                'name' => 'Diya Khaled AbdElBaset',
                'email' => 'diyakab123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Appliance Service',
                'skills' => json_encode(['Washing Machine Repair']),
                'photo' => 'images/profile_photos\pro30.jpg',

            ],
            [
                'provider_id'=>'31',
                'name' => 'Ameen Said Hamdi',
                'email' => 'ameensh123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Appliance Service',
                'skills' => json_encode([ 'Water Heater Repair']),
                'photo' => 'images/profile_photos\pro31.jpg',

            ],
            [
                'provider_id'=>'32',
                'name' => 'Hamza Yasser Rakouf',
                'email' => 'hamzayr123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al-dowahi District',
                'service' => 'Appliance Service',
                'skills' => json_encode(['Refrigerator Repair','Oven Repair']),
                'photo' => 'images/profile_photos\pro32.jpg',

            ],
            [
                'provider_id'=>'33',
                'name' => 'Akram Marwan AbdEllatef',
                'email' => 'akrammab123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al Zohour District',
                'service' => 'Painting Service',
                'skills' => json_encode([ 'Interior Wall Painting',
                'Exterior House Painting',
                'Cabinet Refinishing',
                'Decorative Painting']),
                'photo' => 'images/profile_photos\pro33.jpg',

            ],
            [
                'provider_id'=>'34',
                'name' => 'Eslam Tayseer Shaaban',
                'email' => 'eslamtsh123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'South District',
                'service' => 'Painting Service',
                'skills' => json_encode(['Interior Wall Painting','Decorative Painting','Exterior House Painting']),
                'photo' => 'images/profile_photos\pro34.jpg',

            ],
            [
                'provider_id'=>'35',
                'name' => 'Adnan Taha Magdi',
                'email' => 'adnantm123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al Zohour District',
                'service' => 'Painting Service',
                'skills' => json_encode([ 'Exterior House Painting']),
                'photo' => 'images/profile_photos\pro35.jpg',

            ],
            [
                'provider_id'=>'36',
                'name' => 'Mohand Rami Zakaria',
                'email' => 'mohamedrz123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Painting Service',
                'skills' => json_encode([ 'Decorative Painting']),
                'photo' => 'images/profile_photos\pro36.jpg',

            ],
            [
                'provider_id'=>'37',
                'name' => 'Hazem Nasr Zaki',
                'email' => 'hazemnz123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al-dowahi District',
                'service' => 'Painting Service',
                'skills' => json_encode([  'Exterior House Painting','Cabinet Refinishing']),
                'photo' => 'images/profile_photos\pro37.jpg',

            ],
            [
                'provider_id'=>'38',
                'name' => 'Zaki Fouad Hamed',
                'email' => 'zakifh123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Painting Service',
                'skills' => json_encode(['Interior Wall Painting',
                 'Exterior House Painting',
                 'Cabinet Refinishing',
                 'Decorative Painting']),
                 'photo' => 'images/profile_photos\pro38.jpg',

            ],
            [
                'provider_id'=>'39',
                'name' => 'Eslam Ramy AbdElhameed',
                'email' => 'eslamrab123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al Zohour District',
                'service' => 'Painting Service',
                'skills' => json_encode(['Interior Wall Painting', 'Decorative Painting']),
                'photo' => 'images/profile_photos\pro39.jpg',

            ],
            [
                'provider_id'=>'40',
                'name' => 'Fadel Zakria Nour',
                'email' => 'fadelzn123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Painting Service',
                'skills' => json_encode(['Interior Wall Painting', 'Exterior House Painting']),
                'photo' => 'images/profile_photos\pro40.jpg',

            ],
            [
                'provider_id'=>'41',
                'name' => 'Ali Mansour Mohamed',
                'email' => 'alimm123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Plumbing Service',
                'skills' => json_encode([ 'Fix Leak',
                'Unclog The Drain',
                'Install A New Sink',
                'Replace A Faucet']),
                'photo' => 'images/profile_photos\pro41.jpg',

            ],
            [
                'provider_id'=>'42',
                'name' => 'Ibrahiem Ali Fadel',
                'email' => 'ibrahiemaf123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al Manakh District',
                'service' => 'Plumbing Service',
                'skills' => json_encode(['Fix Leak','Install A New Sink']),
                'photo' => 'images/profile_photos\pro42.jpg',

            ],
            [
                'provider_id'=>'43',
                'name' => 'Tarek Hassan Waleed',
                'email' => 'tarekhw123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'West District',
                'service' => 'Plumbing Service',
                'skills' => json_encode([ 'Unclog The Drain']),
                'photo' => 'images/profile_photos\pro43.jpg',

            ],
            [
                'provider_id'=>'44',
                'name' => 'Karim Mahmoud Gamal',
                'email' => 'karimmg123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al Manakh District',
                'service' => 'Plumbing Service',
                'skills' => json_encode(['Fix Leak', 'Unclog The Drain','Install A New Sink']),
                'photo' => 'images/profile_photos\pro44.jpg',

            ],
            [
                'provider_id'=>'45',
                'name' => 'Sherif Mahmoud Sabri',
                'email' => 'sherifms123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al Zohour District',
                'service' => 'Plumbing Service',
                'skills' => json_encode(['Install A New Sink', 'Replace A Faucet']),
                'photo' => 'images/profile_photos\pro45.jpg',

            ],
            [
                'provider_id'=>'46',
                'name' => 'Mazen Mohamed Radwan',
                'email' => 'makenmr123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'East Port Said District',
                'service' => 'Plumbing Service',
                'skills' => json_encode([ 'Unclog The Drain', 'Replace A Faucet']),
                'photo' => 'images/profile_photos\pro46.jpg',

            ],
            [
                'provider_id'=>'47',
                'name' => 'Amin Badr Fouad',
                'email' => 'aminbf123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' => 'Al-talatini District',
                'service' => 'Plumbing Service',
                'skills' => json_encode(['Fix Leak',
                'Unclog The Drain',
                'Install A New Sink',
                'Replace A Faucet']),
                'photo' => 'images/profile_photos\pro47.jpg',

            ],
            [
                'provider_id'=>'48',
                'name' => 'Akram Hossni Harab',
                'email' => 'akramhh123@gmail.com',
                'password' => Hash::make('22222222'),
                'phone' => '01122334455',
                'area' =>'Al Manakh District',
                'service' => 'Plumbing Service',
                'skills' => json_encode(['Fix Leak']),
                'photo' => 'images/profile_photos\pro48.jpg',

            ],
        ]);
    }
}
